server:
  port: 8081
spring:
  application:
    name: taskjpa
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/task?allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0
    timeout:
      seconds: 10000
    jedis:
      pool:
        max-active: 1024
        max-wait:
          seconds: 10000
        max-idle: 200
        min-idle: 1800000
        
        
        
        
authorizationfilter:
  requestUriList[0]: /user/register
  requestUriList[1]: /user/login
myTask:
  apiKey: task0408 
  isAuth: 0 #是否检验接口 0不检验，1检验
  isSaveRequestLogs: 0 #是否保存请求日志 0否，1是
        
     
        
        
        
          
        
      
      
    
      